;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_str
	.export		_main
	.export		_RESETVEC

.segment	"DATA"

_str:
	.addr	L0001
.segment	"RESETVEC"
_RESETVEC:
	.word	$0F00
	.word	$0600
	.word	$0000
.segment	"DATA"

.segment	"RODATA"

L0001:
	.byte	$50,$72,$69,$6E,$74,$69,$6E,$67,$21,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; *(uint8_t *)(CHROUT) = 'H';
;
	ldx     #$00
	lda     #$48
	sta     $FF00
;
; *(uint8_t *)(CHROUT) = 'e';
;
	ldx     #$00
	lda     #$65
	sta     $FF00
;
; *(uint8_t *)(CHROUT) = 'l';
;
	ldx     #$00
	lda     #$6C
	sta     $FF00
;
; *(uint8_t *)(CHROUT) = 'l';
;
	ldx     #$00
	lda     #$6C
	sta     $FF00
;
; *(uint8_t *)(CHROUT) = 'o';
;
	ldx     #$00
	lda     #$6F
	sta     $FF00
;
; *(uint8_t *)(CHROUT) = '\n';
;
	ldx     #$00
	lda     #$0A
	sta     $FF00
;
; for (;;);
;
L0016:	jmp     L0019
L0018:	jmp     L0016
L0019:	jmp     L0018
;
; }
;
	rts

.endproc

